# Generated by Django 3.2.12 on 2022-10-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buy_sell', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('number', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shares')),
            ],
        ),
        migrations.CreateModel(
            name='Price_Changes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.shares')),
            ],
        ),
    ]
